name: 'Enhancement'
description: 'Suggest an enhancement for an existing feature'
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: 'textarea'
    id: 'enhancement-description'
    attributes:
      label: 'What is the enhancement you are proposing?'
      description: 'A clear and concise description of the enhancement.'
    validations:
      required: true
  - type: 'textarea'
    id: 'additional-context'
    attributes:
      label: 'Additional context'
      description: 'Add any other context or screenshots about the enhancement here.'
    validations:
      required: false
